[package]
name = "glslopt"
version = "0.1.11"
authors = ["Jamie Nicol <jnicol@mozilla.com>"]
edition = "2018"
license = "MIT"
description = "Optimizes GLSL shader code"
keywords = ["opengl", "gl", "gles", "glsl", "shader"]
repository = "https://github.com/jamienicol/glslopt-rs"

[build-dependencies]
cc = "1.0"
